In [1]:
import matplotlib.pyplot as plt
%matplotlib qt
import numpy as np
import pickle
import pandas as pd

from pathlib import Path
from src.models.sklearn_models import RandomForestModel, XGBModel
from src.models.keras_models import ConcatenatedModulesModel
from src.visualization.radar_chart import radial_chart

In [2]:


rf = RandomForestModel()
xgb = XGBModel()
dnn = ConcatenatedModulesModel("ConcatenatedDNN")
cnn = ConcatenatedModulesModel("ConcatenatedCNN")
bilstm = ConcatenatedModulesModel("ConcatenatedBiLSTM")

column_names = ['chlid', 'chl_a', 'chl_b', 'chc12', 'fucox', 'hxfcx', 'btfcx', 'diadi',
       'allox', 'diato', 'zeaxa', 'betac', 'perid']

graph_names = ['chlide', 'chla', 'chlb', 'chlc12', 'fuco', "19'hxfuco", "19'btfuco", 'diadino',
       'allo', 'diato', 'zea', 'betac', 'peri']


rename_models = {
    "ConcatenatedDNN": "DNN",
    "ConcatenatedCNN": "CNN",
    "ConcatenatedBiLSTM": "BiLSTM",
    "rf": "RF",
    "xgb": "XGB",
}

colors = ['#1E5799', '#AAAAAA', '#00A0B0', '#F0AD4E', '#C85217']

markers = ['^', 's', 'p', 'p', 'p']
linestyles = ['-', '--', ':', '-.', ':']

In [3]:
models = [cnn, dnn, bilstm, xgb, rf]
# models = [cnn]

experiment_name = '13_wl_final'
experiment_name = '5_wl_final'

In [30]:
path_experiments =  Path(f'../../experiments/{experiment_name}')
paths_metrics = [p / 'metrics' for p in path_experiments.iterdir()]

In [31]:
# Load metrics:
metrics_test = {model.name: { p.parent.name :pd.read_csv(p/ (model.name + '_test.csv'), index_col=0) for p in paths_metrics} for model in models}
metrics_train = {model.name: { p.parent.name :pd.read_csv(p/ (model.name + '_train.csv'), index_col=0) for p in paths_metrics} for model in models}

In [32]:
metrics_test_mean = {model_name:  pd.concat(mets.values()).groupby(level=0).mean() for model_name, mets in metrics_test.items()}
metrics_train_mean = {model_name:  pd.concat(mets.values()).groupby(level=0).mean() for model_name, mets in metrics_train.items()}
metrics_test_mean_mean = pd.DataFrame({model_name: val.mean(axis=1) for model_name, val in metrics_test_mean.items()})
metrics_train_mean_mean = pd.DataFrame({model_name: val.mean(axis=1) for model_name, val in metrics_train_mean.items()})

In [33]:
# select values to plot (R2 here)
r2_mets = pd.DataFrame(ds.loc['R2',:].rename(model_name) for model_name, ds in metrics_test_mean.items())

In [34]:
r2_mets = r2_mets.sort_values(axis=1, by='ConcatenatedCNN', ascending=False)
r2_mets = r2_mets.rename(dict(zip(column_names, graph_names)), axis=1)
r2_mets = r2_mets.rename(rename_models, axis=0)

In [35]:
# pigments = np.array(['chlide_a', 'chla   ', 'chlb      ', 'chlc1+c2              ', 'fucox           ', "19'hxfcx               ", 
#                      "19'btfcx         ", "             diadino", "        allox", "           diatox", "            zeaxan", "              beta_car",
#                      "               peridinin"])

In [36]:
radial_chart(r2_mets.values, r2_mets.columns, r2_mets.index, colors=colors, markers=markers, linestyles=linestyles, title='', save=None)

In [12]:
r2_mets

,chlc12,chla,betac,diadino,fuco,peri,chlb,diato,chlide,19'hxfuco,allo,19'btfuco,zea
XGB,0.920872,0.912795,0.889833,0.860384,0.896103,0.854783,0.770071,0.743582,0.664891,0.551984,0.555442,0.473469,0.429347
CNN,0.917762,0.908198,0.895696,0.889668,0.888257,0.829351,0.780298,0.779888,0.766274,0.723424,0.630238,0.476286,0.464285

In [4]:
#  same model different wavelengths:

experiment_name_cnn = '13_wl_final'
experiment_name_cnn_ast = '5_wl_final'

path_experiments_cnn =  Path(f'../../experiments/{experiment_name_cnn}')
paths_metrics_cnn = [p / 'metrics' for p in path_experiments_cnn.iterdir()]

path_experiments_cnn_ast =  Path(f'../../experiments/{experiment_name_cnn_ast}')
paths_metrics_cnn_ast = [p / 'metrics' for p in path_experiments_cnn_ast.iterdir()]

# Load metrics:
metrics_test = {"CNN": { p.parent.name :pd.read_csv(p/ (cnn.name + '_test.csv'), index_col=0) for p in paths_metrics_cnn},
                "CNN*": { p.parent.name :pd.read_csv(p/ (cnn.name + '_test.csv'), index_col=0) for p in paths_metrics_cnn_ast}
               }
metrics_train = {"CNN": { p.parent.name :pd.read_csv(p/ (cnn.name + '_train.csv'), index_col=0) for p in paths_metrics_cnn},
                "CNN*": { p.parent.name :pd.read_csv(p/ (cnn.name + '_train.csv'), index_col=0) for p in paths_metrics_cnn_ast}
               }

In [5]:
metrics_test_mean = {model_name:  pd.concat(mets.values()).groupby(level=0).mean() for model_name, mets in metrics_test.items()}
metrics_train_mean = {model_name:  pd.concat(mets.values()).groupby(level=0).mean() for model_name, mets in metrics_train.items()}
metrics_test_mean_mean = pd.DataFrame({model_name: val.mean(axis=1) for model_name, val in metrics_test_mean.items()})
metrics_train_mean_mean = pd.DataFrame({model_name: val.mean(axis=1) for model_name, val in metrics_train_mean.items()})

In [6]:
# select values to plot (R2 here)
r2_mets = pd.DataFrame(ds.loc['R2',:].rename(model_name) for model_name, ds in metrics_test_mean.items())

In [7]:
r2_mets = r2_mets.sort_values(axis=1, by='CNN', ascending=False)
r2_mets = r2_mets.rename(dict(zip(column_names, graph_names)), axis=1)
r2_mets = r2_mets.rename(rename_models, axis=0)

In [8]:
r2_mets

,chlc12,chla,betac,diadino,fuco,peri,chlb,diato,chlide,19'hxfuco,allo,19'btfuco,zea
CNN,0.917762,0.908198,0.895696,0.889668,0.888257,0.829351,0.780298,0.779888,0.766274,0.723424,0.630238,0.476286,0.464285
CNN*,0.909006,0.892479,0.885713,0.883771,0.895590,0.857889,0.755052,0.742748,0.757527,0.711854,0.579313,0.391665,0.550700

In [9]:
colors = ['#1E5799', '#00A0B0']

radial_chart(r2_mets.values, r2_mets.columns, r2_mets.index, colors=colors, markers=markers, linestyles=linestyles, title='', save=None)